# Generated by Django 4.0.5 on 2022-12-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='dislike',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='count',
            name='like',
            field=models.CharField(max_length=100),
        ),
    ]
